Make asdf-mockery multi platform compatible

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,45 +4,61 @@ set -eo pipefail
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 
 test -n "$ASDF_INSTALL_VERSION" || {
-	echo 'Missing ASDF_INSTALL_VERSION'
-	exit 1
+    echo 'Missing ASDF_INSTALL_VERSION'
+    exit 1
 }
 
 test -n "$ASDF_INSTALL_PATH" || {
-	echo 'Missing ASDF_INSTALL_PATH'
-	exit 1
+    echo 'Missing ASDF_INSTALL_PATH'
+    exit 1
+}
+
+_get_os() {
+    uname | tr '[:upper:]' '[:lower:]'
 }
 
 _get_arch() {
-	uname | tr '[:upper:]' '[:lower:]'
+    arch=$(uname -m)
+    case $arch in
+
+    x86_64)
+        arch="x86_64"
+        ;;
+    aarch64)
+        arch="arm64"
+        ;;
+    esac
+    echo $arch
 }
 
 _get_download_url() {
-	local -r version="$1"
-	local -r platform="$2"
+    local -r version="$1"
+    local -r os="$2"
+    local -r arch="$3"
 
-	echo "https://github.com/vektra/mockery/releases/download/v${version}/mockery_${version}_${platform}_x86_64.tar.gz"
+    echo "https://github.com/vektra/mockery/releases/download/v${version}/mockery_${version}_${os}_${arch}.tar.gz"
 }
 
 install() {
-	local -r install_type=$1
-	local -r version=$2
-	local -r install_path=$3
-	local -r tar_install_path="$install_path/mockery-v$version.tgz"
-	local -r bin_install_path="$install_path/bin"
-	local -r tmp_install_path="mockery-v$version"
-	local -r platform="$(_get_arch)"
-	local -r download_url="$(_get_download_url "$version" "$platform")"
-	local -r bin_path="$bin_install_path/mockery"
+    local -r install_type=$1
+    local -r version=$2
+    local -r install_path=$3
+    local -r tar_install_path="$install_path/mockery-v$version.tgz"
+    local -r bin_install_path="$install_path/bin"
+    local -r tmp_install_path="mockery-v$version"
+    local -r os="$(_get_os)"
+    local -r arch="$(_get_arch)"
+    local -r download_url="$(_get_download_url "$version" "$os" "$arch")"
+    local -r bin_path="$bin_install_path/mockery"
 
-	mkdir -p "$bin_install_path"
-	echo "Downloading mockery from $download_url"
-	curl -Ls "$download_url" -o "$tar_install_path"
-	mkdir "$tmp_install_path"
-	tar -xzf "$tar_install_path" -C "$tmp_install_path"
-	cp "$tmp_install_path/mockery" "$bin_path"
-	rm -rf "$tmp_install_path"
-	chmod +x "$bin_path"
+    mkdir -p "$bin_install_path"
+    echo "Downloading mockery from $download_url"
+    curl -Ls "$download_url" -o "$tar_install_path"
+    mkdir "$tmp_install_path"
+    tar -xzf "$tar_install_path" -C "$tmp_install_path"
+    cp "$tmp_install_path/mockery" "$bin_path"
+    rm -rf "$tmp_install_path"
+    chmod +x "$bin_path"
 }
 
 install "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
